server:
  port: 8082

spring:
  application:
    name: Axon Demo Command
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  # spring data - postgres configuration
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/axontestcommand
    username: postgres
    password: password

