
-- CREATE DATABASE FOR COMMAND SERVICE
CREATE DATABASE axontestcommand;
GRANT ALL PRIVILEGES ON DATABASE axontestcommand TO postgres;

-- CREATE DATABASE FOR QUERY SERVICE
CREATE DATABASE axontestquery;
GRANT ALL PRIVILEGES ON DATABASE axontestquery TO postgres;