version: "3.1"

services:
  # PostgreSQL
  postgreslq:
    container_name: microservices-postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

  # Rabbit MQ
  rabbitmq:
    container_name: microservices-rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitUser
      RABBITMQ_DEFAULT_PASS: rabbitPass
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"

  ## observability ##

  # ELK - elastic search
  elasticsearch:
    container_name: microservices-elastic_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    environment:
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - ELASTIC_PASSWORD=password
      - KIBANA_PASSWORD=password
      - CLUSTER_NAME=es1
      - ES_PORT=9200
      - KIBANA_PORT=5601
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - es-net
    ports:
      - "9200:9200"

  # ELK - kibana
  kibana:
    container_name: microservices-kibana
    image: docker.elastic.co/kibana/kibana:8.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  # ELK - logstash
  logstash:
    container_name: microservices-logstash
    image: docker.elastic.co/logstash/logstash:8.6.1
    volumes:
      - ./observability/logstash/logstash-elk.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../../logs:/logs
    networks:
      - es-net
    depends_on:
      - elasticsearch

      # prometheus
  prometheus:
    container_name: microservices-prometheus
    image: bitnami/prometheus:latest
    user: 1001:1001
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  # grafana
  grafana:
    container_name: microservices-grafana
    image: grafana/grafana-oss:9.3.6-ubuntu
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - '3000:3000'

networks:
  es-net:
    driver: bridge